env = QT_FFMPEG_DECODING_HW_DEVICE_TYPES,none

# ==============================================================================
# WINDOW RULES (Assigning Apps to Workspaces by Class and Title)
# ==============================================================================

# Workspace 1: Main Workstation
#windowrulev2 = workspace 1, class:^(zen-browser)$
#windowrulev2 = workspace 1, class:^(zen)$
#windowrulev2 = workspace 1, title:^(kitty-fastfetch)$
#windowrulev2 = workspace 1, title:^(yazi)$

# Workspace 2: System & Media Monitoring
#windowrulev2 = workspace 2, title:^(rmpc)$
#windowrulev2 = workspace 2, title:^(btop)$
#windowrulev2 = workspace 2, title:^(cava)$

# Workspace 3: Aesthetics / Screensaver
#windowrulev2 = workspace 3, title:^(pipes)$


# ==============================================================================
# AUTOSTART EXECUTION (Launching Apps Silent on Boot)
# ==============================================================================

# Workspace 1 Apps
#exec-once = [workspace 1 silent] zen-browser
#exec-once = [workspace 1 silent] kitty --title kitty-fastfetch -e fastfetch
#exec-once = [workspace 1 silent] kitty --title yazi -e yazi

# Workspace 2 Apps
#exec-once = [workspace 2 silent] mpd
#exec-once = [workspace 2 silent] kitty --title rmpc -e rmpc
#exec-once = [workspace 2 silent] kitty --title btop -e btop
#exec-once = [workspace 2 silent] kitty --title cava -e cava

# Workspace 3 Apps
#exec-once = [workspace 3 silent] kitty --title pipes -e pipes.sh


# Force rmpc and cava onto workspace 2 and split them
#windowrulev2 = workspace 2, title:^(rmpc-window)$
#windowrulev2 = workspace 2, title:^(cava-window)$
#windowrulev2 = workspace 2, title:^(btop-window)$
